/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Startup;

import User.*;
import Error.ErrorPage;
import Startup.loginform;
import config.Session;
import config.dbConnector;
import config.passHash;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Chris
 */
public class forgotPassword extends javax.swing.JFrame {
    private String userEmail;
    
    public forgotPassword() {
        initComponents();
    }
    
    
    Color bodycolor = new Color(0,204,204);
    Color nav = new  Color(0,153,204);
    Color bodycolor1 = new Color(255,51,51);
    Color nav1 = new  Color(255,102,102);
    Color sh = new  Color(51,204,255);
    Color sh1 = new  Color(153,204,255);
    Color sm = new  Color(102,255,0);
    Color sm1 = new  Color(153,255,153);

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userpanel = new javax.swing.JPanel();
        cl = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        changePass = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cp = new javax.swing.JPasswordField();
        question = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submit = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        search = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userpanel.setBackground(new java.awt.Color(241, 242, 247));
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl.setBackground(new java.awt.Color(255, 51, 51));
        cl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clMouseExited(evt);
            }
        });
        cl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Clear");
        cl.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 20));

        userpanel.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 180, 40));

        changePass.setBackground(new java.awt.Color(0, 204, 204));
        changePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePass.setEnabled(false);
        changePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePassMouseExited(evt);
            }
        });
        changePass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Change Pass");
        changePass.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        userpanel.add(changePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 180, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Answer");
        userpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        cp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cp.setBorder(null);
        cp.setEnabled(false);
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });
        userpanel.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 220, 44));

        question.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userpanel.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 340, 50));

        newpass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpass.setBorder(null);
        newpass.setEnabled(false);
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        userpanel.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 210, 44));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pen.png"))); // NOI18N
        userpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reset Password");
        userpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turn-left_10977010.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        userpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        answer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        answer.setEnabled(false);
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        userpanel.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 340, 50));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setText("Confirm Password");
        userpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("New Password");
        userpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 30));

        submit.setBackground(new java.awt.Color(102, 255, 0));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Submit");
        submit.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));

        userpanel.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 100, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Please enter your email to search for your account.");
        userpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 420, 30));

        email.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        userpanel.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, 50));

        search.setBackground(new java.awt.Color(51, 204, 255));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.setEnabled(false);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Search");
        search.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));

        userpanel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, 40));

        getContentPane().add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseClicked
        String password1 = new String(cp.getPassword());
        String cpassword = new String(newpass.getPassword());
        cp.setText("");
        newpass.setText("");
    }//GEN-LAST:event_clMouseClicked

    private void clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseEntered
        cl.setBackground(nav1);
    }//GEN-LAST:event_clMouseEntered

    private void clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseExited
        cl.setBackground(bodycolor1);
    }//GEN-LAST:event_clMouseExited

    private void changePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseClicked
        String password1 = new String(newpass.getPassword());
        String cpassword = new String(cp.getPassword());
        String userInput = email.getText();

        if (password1.isEmpty() && cpassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(newpass.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Password must be atleast 8 characters long");
            newpass.setText("");
        }else{
            try {
                dbConnector dbc = new dbConnector();

                    String pass = passHash.hashPassword(newpass.getText());
                    String pass2 = passHash.hashPassword(cp.getText());

                    if (pass.equals(pass2)) {
                        dbc.updateData("UPDATE tbl_admin SET u_password = '" + pass + "', u_cpassword = '"+ pass2 +"' WHERE u_email = '"+userInput+"'");
                        JOptionPane.showMessageDialog(null, "Change Password `Successfully!");
                        loginform lf = new loginform();
                        lf.setVisible(true);
                        this.dispose();
                    }else if(!newpass.getText().equals(cp.getText())){
                        JOptionPane.showMessageDialog(null, "Password not Matches");
                        newpass.setText("");
                        cp.setText("");
                    }
            } catch (NoSuchAlgorithmException ex){
                System.out.println(""+ex);
            }

        }
    }//GEN-LAST:event_changePassMouseClicked

    private void changePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseEntered
        changePass.setBackground(nav);
    }//GEN-LAST:event_changePassMouseEntered

    private void changePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseExited
        changePass.setBackground(bodycolor);
    }//GEN-LAST:event_changePassMouseExited

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    loginform lf = new loginform();
    lf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
    String userInput = email.getText();
    String an = answer.getText();
    dbConnector db = new dbConnector();
    
    if(an.isEmpty()){
       JOptionPane.showMessageDialog(this, "Input an answer first!", "Error", JOptionPane.ERROR_MESSAGE);
    }else{
        try {
            String query = "SELECT u_questions, u_answers FROM tbl_admin WHERE u_email = '" + userInput + "'";
            ResultSet rs = db.getData(query);

            if (rs.next()) {
                question.setText(""+rs.getString("u_questions"));
                String storedAnswer = rs.getString("u_answers");

                String userAnswer = answer.getText();

                if (userAnswer != null && userAnswer.equalsIgnoreCase(storedAnswer)) {
                    JOptionPane.showMessageDialog(this, "Security answer correct! Proceeding to reset password.");
                    newpass.setEnabled(true);
                    cp.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect answer!", "Error", JOptionPane.ERROR_MESSAGE);
                    newpass.setEnabled(false);
                    cp.setEnabled(false);
                    answer.setText("");
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    }//GEN-LAST:event_submitMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        String userInput = email.getText();
        if (userInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        dbConnector db = new dbConnector();
        try {
            String query = "SELECT u_questions, u_email FROM tbl_admin WHERE u_email = '" + userInput + "'";
            ResultSet rs = db.getData(query);

            if (rs.next()) {
                String storedQuestion = rs.getString("u_questions");
                if (storedQuestion == null || storedQuestion.equalsIgnoreCase("No stored security questions") || storedQuestion.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "No security question found, cannot proceed to reset password!", "Error", JOptionPane.ERROR_MESSAGE);
                    question.setText("");
                    answer.setText("");
                    answer.setEnabled(false);
                }else{
                    question.setText(""+rs.getString("u_questions"));
                    JOptionPane.showMessageDialog(null, "Account Found");
                    answer.setEnabled(true);
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Account not found!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_searchMouseClicked

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        search.setBackground(sh1);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        search.setBackground(sh);
    }//GEN-LAST:event_searchMouseExited

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        submit.setBackground(sm1);
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        submit.setBackground(sm);
    }//GEN-LAST:event_submitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    public javax.swing.JPanel changePass;
    private javax.swing.JPanel cl;
    private javax.swing.JPasswordField cp;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JLabel question;
    public javax.swing.JPanel search;
    private javax.swing.JPanel submit;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables

}
