/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.awt.Color;

/**
 *
 * @author Chris
 */
public class evaluate extends javax.swing.JFrame {

    /**
     * Creates new form evaluate
     */
    public evaluate() {
        initComponents();
    }
    
    Color bodycolor = new Color(0,204,204);
    Color nav = new  Color(0,153,204);
    Color bodycolor1 = new Color(255,51,51);
    Color nav1 = new  Color(255,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rp = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cm6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tn = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        eva26 = new javax.swing.JCheckBox();
        eva27 = new javax.swing.JCheckBox();
        eva6 = new javax.swing.JCheckBox();
        eva11 = new javax.swing.JCheckBox();
        eva16 = new javax.swing.JCheckBox();
        eva21 = new javax.swing.JCheckBox();
        over5 = new javax.swing.JCheckBox();
        eva5 = new javax.swing.JCheckBox();
        eva7 = new javax.swing.JCheckBox();
        eva12 = new javax.swing.JCheckBox();
        eva17 = new javax.swing.JCheckBox();
        eva22 = new javax.swing.JCheckBox();
        eva2 = new javax.swing.JCheckBox();
        eva3 = new javax.swing.JCheckBox();
        eva4 = new javax.swing.JCheckBox();
        eva8 = new javax.swing.JCheckBox();
        eva9 = new javax.swing.JCheckBox();
        eva10 = new javax.swing.JCheckBox();
        eva13 = new javax.swing.JCheckBox();
        eva14 = new javax.swing.JCheckBox();
        eva15 = new javax.swing.JCheckBox();
        eva18 = new javax.swing.JCheckBox();
        eva19 = new javax.swing.JCheckBox();
        eva20 = new javax.swing.JCheckBox();
        eva23 = new javax.swing.JCheckBox();
        eva24 = new javax.swing.JCheckBox();
        eva25 = new javax.swing.JCheckBox();
        eva28 = new javax.swing.JCheckBox();
        eva29 = new javax.swing.JCheckBox();
        eva30 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jt = new javax.swing.JTextField();
        cm1 = new javax.swing.JTextField();
        cm2 = new javax.swing.JTextField();
        cm3 = new javax.swing.JTextField();
        cm4 = new javax.swing.JTextField();
        cm5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        eva1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        over4 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        over3 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        over2 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        over1 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        cnl = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        save = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 242, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 216, 218));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard_1355683.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Task Evaluation");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 200, 40));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 120, 30));

        empname.setEditable(false);
        jPanel1.add(empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 180, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Department:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 120, 30));

        dep.setEditable(false);
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });
        jPanel1.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 180, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Review Period:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 120, 30));
        jPanel1.add(rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 180, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("6. Adaptability (Adjusts quickly to changes and new challenges)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 410, 30));

        cm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm6ActionPerformed(evt);
            }
        });
        jPanel1.add(cm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 180, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Job Title:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 120, 30));

        tn.setEditable(false);
        tn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnActionPerformed(evt);
            }
        });
        jPanel1.add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 180, 30));

        tid.setEditable(false);
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        jPanel1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 180, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Task ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 120, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Task Name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 120, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Comments");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 120, 30));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setText(" (Outstanding) – Consistently exceeds expectations.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, 340, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("2. Work Quality (Produces error-free, high-quality work)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 360, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setText("3. Productivity (Delivers high volume of work efficiently)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 360, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setText("4. Problem-Solving (Identifies issues and develops effective solutions)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 450, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setText("5. Communication (Clearly conveys information verbally and in writing)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 450, 30));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Areas for Improvement");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 190, 30));

        eva26.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva26.setText("1");
        jPanel1.add(eva26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, 30));

        eva27.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva27.setText("2");
        jPanel1.add(eva27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, 30));

        eva6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva6.setText("1");
        jPanel1.add(eva6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, 30));

        eva11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva11.setText("1");
        jPanel1.add(eva11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, 30));

        eva16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva16.setText("1");
        jPanel1.add(eva16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, 30));

        eva21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva21.setText("1");
        jPanel1.add(eva21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, 30));

        over5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        over5.setText("5");
        jPanel1.add(over5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, -1, 30));

        eva5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva5.setText("5");
        jPanel1.add(eva5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, 30));

        eva7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva7.setText("2");
        jPanel1.add(eva7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, 30));

        eva12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva12.setText("2");
        jPanel1.add(eva12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, 30));

        eva17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva17.setText("2");
        jPanel1.add(eva17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, 30));

        eva22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva22.setText("2");
        jPanel1.add(eva22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, 30));

        eva2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva2.setText("2");
        jPanel1.add(eva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, 30));

        eva3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva3.setText("3");
        jPanel1.add(eva3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, 30));

        eva4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva4.setText("4");
        jPanel1.add(eva4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, 30));

        eva8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva8.setText("3");
        jPanel1.add(eva8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, 30));

        eva9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva9.setText("4");
        jPanel1.add(eva9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, 30));

        eva10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva10.setText("5");
        jPanel1.add(eva10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, 30));

        eva13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva13.setText("3");
        jPanel1.add(eva13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, 30));

        eva14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva14.setText("4");
        jPanel1.add(eva14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, 30));

        eva15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva15.setText("5");
        jPanel1.add(eva15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, 30));

        eva18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva18.setText("3");
        jPanel1.add(eva18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, 30));

        eva19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva19.setText("4");
        jPanel1.add(eva19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, 30));

        eva20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva20.setText("5");
        jPanel1.add(eva20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, 30));

        eva23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva23.setText("3");
        jPanel1.add(eva23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, 30));

        eva24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva24.setText("4");
        jPanel1.add(eva24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, -1, 30));

        eva25.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva25.setText("5");
        jPanel1.add(eva25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, -1, 30));

        eva28.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva28.setText("3");
        jPanel1.add(eva28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, 30));

        eva29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva29.setText("4");
        jPanel1.add(eva29, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, -1, 30));

        eva30.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva30.setText("5");
        jPanel1.add(eva30, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, -1, 30));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Rating (1-5)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 120, 30));

        jt.setEditable(false);
        jt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtActionPerformed(evt);
            }
        });
        jPanel1.add(jt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 180, 30));

        cm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm1ActionPerformed(evt);
            }
        });
        jPanel1.add(cm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 180, 30));

        cm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm2ActionPerformed(evt);
            }
        });
        jPanel1.add(cm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 180, 30));

        cm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm3ActionPerformed(evt);
            }
        });
        jPanel1.add(cm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 180, 30));

        cm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm4ActionPerformed(evt);
            }
        });
        jPanel1.add(cm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 180, 30));

        cm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm5ActionPerformed(evt);
            }
        });
        jPanel1.add(cm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 180, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Evaluation Criteria");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 140, 30));

        eva1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        eva1.setText("1");
        jPanel1.add(eva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setText("1. Job Performance (Completes tasks on time & accurately)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 390, 30));

        over4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        over4.setText("4");
        jPanel1.add(over4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, -1, 30));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("(Exceeds Expectations) – Often performs above requirements.");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 370, 400, 30));

        over3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        over3.setText("3");
        jPanel1.add(over3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, -1, 30));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("(Meets Expectations) – Fully meets job standards.");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 410, 30));

        over2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        over2.setText("2");
        jPanel1.add(over2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, -1, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setText("(Needs Improvement) – Falls short in key areas.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 310, 30));

        over1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        over1.setText("1");
        jPanel1.add(over1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, -1, 30));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setText("(Unsatisfactory) – Fails to meet basic expectations.");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 460, 340, 30));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Overall Rating ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 140, 30));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 400, 110));

        cnl.setBackground(new java.awt.Color(255, 51, 51));
        cnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnlMouseExited(evt);
            }
        });
        cnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Cancel");
        cnl.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        jPanel1.add(cnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 180, 40));

        save.setBackground(new java.awt.Color(0, 204, 204));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Save");
        save.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depActionPerformed

    private void cm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm6ActionPerformed

    private void tnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void jtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtActionPerformed

    private void cm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm1ActionPerformed

    private void cm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm2ActionPerformed

    private void cm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm3ActionPerformed

    private void cm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm4ActionPerformed

    private void cm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm5ActionPerformed

    private void cnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseClicked
        employeeTask et = new employeeTask();
        et.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cnlMouseClicked

    private void cnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseEntered
        cnl.setBackground(nav1);
    }//GEN-LAST:event_cnlMouseEntered

    private void cnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseExited
        cnl.setBackground(bodycolor1);
    }//GEN-LAST:event_cnlMouseExited

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
//        String progress = pp.getText();
//
//        if (progress.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Progress percentage fields is required!", "Error", JOptionPane.ERROR_MESSAGE);
//        } else if(!progress.matches("\\d+")) {
//            JOptionPane.showMessageDialog(null, "Progress percentage should contain only numbers!");
//        } else {
//            int progressValue = Integer.parseInt(progress);
//
//            if (progressValue > 100) {
//                JOptionPane.showMessageDialog(this, "Progress cannot exceed 100%!", "Invalid Value", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//
//            String status;
//            if (progressValue == 100) {
//                status = "Completed";
//            } else {
//                status = "Active";
//            }
//
//            dbConnector db = new dbConnector();
//            db.updateData("UPDATE tbl_task SET t_status = '"+status+"', t_progress = '"+progress+"' WHERE t_id = '"+tid.getText()+"'");
//
//            Session sess = Session.getInstance();
//            db.logActivity(sess.getUid(), "Updated a task: " + tn.getText());
//
//            JOptionPane.showMessageDialog(this, "Updated Task Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
//            employeeTask et = new employeeTask();
//            et.setVisible(true);
//            this.dispose();
//        }
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setBackground(nav);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setBackground(bodycolor);
    }//GEN-LAST:event_saveMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evaluate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evaluate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evaluate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evaluate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new evaluate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField cm1;
    private javax.swing.JTextField cm2;
    private javax.swing.JTextField cm3;
    private javax.swing.JTextField cm4;
    private javax.swing.JTextField cm5;
    private javax.swing.JTextField cm6;
    private javax.swing.JPanel cnl;
    public javax.swing.JTextField dep;
    public javax.swing.JTextField empname;
    private javax.swing.JCheckBox eva1;
    private javax.swing.JCheckBox eva10;
    private javax.swing.JCheckBox eva11;
    private javax.swing.JCheckBox eva12;
    private javax.swing.JCheckBox eva13;
    private javax.swing.JCheckBox eva14;
    private javax.swing.JCheckBox eva15;
    private javax.swing.JCheckBox eva16;
    private javax.swing.JCheckBox eva17;
    private javax.swing.JCheckBox eva18;
    private javax.swing.JCheckBox eva19;
    private javax.swing.JCheckBox eva2;
    private javax.swing.JCheckBox eva20;
    private javax.swing.JCheckBox eva21;
    private javax.swing.JCheckBox eva22;
    private javax.swing.JCheckBox eva23;
    private javax.swing.JCheckBox eva24;
    private javax.swing.JCheckBox eva25;
    private javax.swing.JCheckBox eva26;
    private javax.swing.JCheckBox eva27;
    private javax.swing.JCheckBox eva28;
    private javax.swing.JCheckBox eva29;
    private javax.swing.JCheckBox eva3;
    private javax.swing.JCheckBox eva30;
    private javax.swing.JCheckBox eva4;
    private javax.swing.JCheckBox eva5;
    private javax.swing.JCheckBox eva6;
    private javax.swing.JCheckBox eva7;
    private javax.swing.JCheckBox eva8;
    private javax.swing.JCheckBox eva9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jt;
    private javax.swing.JCheckBox over1;
    private javax.swing.JCheckBox over2;
    private javax.swing.JCheckBox over3;
    private javax.swing.JCheckBox over4;
    private javax.swing.JCheckBox over5;
    public com.toedter.calendar.JDateChooser rp;
    public javax.swing.JPanel save;
    public javax.swing.JTextField tid;
    public javax.swing.JTextField tn;
    // End of variables declaration//GEN-END:variables
}
