/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Error.ErrorPage;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Chris
 */
public class editDepartmentForm extends javax.swing.JFrame {

    /**
     * Creates new form createUserForm
     */
    public editDepartmentForm() {
        initComponents();
        loadEmployees();
    }
      
    private HashMap<String, Integer> employeeMap = new HashMap<>();    
    private void loadEmployees() {
        try {
            dbConnector db = new dbConnector();
            String query = "SELECT u_id, u_fname, u_lname FROM tbl_admin WHERE u_type = 'Employee' ORDER BY u_fname";
            ResultSet rs = db.getData(query);

            dphead.removeAllItems();
            employeeMap.clear();

            dphead.addItem("Please Select Employee");

            boolean hasEmployees = false;
            while (rs.next()) {
                hasEmployees = true;
                int userId = rs.getInt("u_id");
                String fullName = rs.getString("u_fname") + " " + rs.getString("u_lname");
                dphead.addItem(fullName);
                employeeMap.put(fullName, userId);
            }

            if (!hasEmployees) {
                dphead.addItem("N/A");
                JOptionPane.showMessageDialog(this, 
                    "No employees available. Please create an user with employee type first.", 
                    "No Employees Found", 
                    JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading employees: " + e.getMessage());
        }
    }
    Color bodycolor = new Color(0,204,204);
    Color nav = new  Color(0,153,204);
    Color bodycolor1 = new Color(255,51,51);
    Color nav1 = new  Color(255,102,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        totalemp = new javax.swing.JTextField();
        depid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        save = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dphead = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cnl = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dpname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(241, 242, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Edit Department");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 200, 40));

        totalemp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        totalemp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalemp.setBorder(null);
        totalemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalempActionPerformed(evt);
            }
        });
        jPanel3.add(totalemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 220, 44));

        depid.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        depid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        depid.setBorder(null);
        depid.setEnabled(false);
        depid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depidActionPerformed(evt);
            }
        });
        jPanel3.add(depid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setText("Total Employees");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 30));

        save.setBackground(new java.awt.Color(0, 204, 204));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Update");
        save.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 180, 40));

        dphead.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dphead.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Employee" }));
        dphead.setBorder(null);
        dphead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dphead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpheadActionPerformed(evt);
            }
        });
        jPanel3.add(dphead, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 220, 44));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setText("Department Head");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 30));

        cnl.setBackground(new java.awt.Color(255, 51, 51));
        cnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnlMouseExited(evt);
            }
        });
        cnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Cancel");
        cnl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        jPanel3.add(cnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 180, 40));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel18.setText("Department ID:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-friend_12391319.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(1, 216, 218));
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        dpname.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dpname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dpname.setBorder(null);
        dpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpnameActionPerformed(evt);
            }
        });
        jPanel3.add(dpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 220, 44));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel19.setText("Department Name");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void totalempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalempActionPerformed

    private void depidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depidActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        String departmentname = depid.getText();
        String totalemployees = totalemp.getText();
        String selectedHead = dphead.getSelectedItem().toString();  
        
        if (departmentname.isEmpty() || totalemployees.isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if ("Please Select Employee".equals(selectedHead) || "N/A".equals(selectedHead)) {
        JOptionPane.showMessageDialog(this, "Please select a valid employee", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            dbConnector db = new dbConnector(); 
            Integer depId = null;
            Integer userId = employeeMap.get(selectedHead);

            try {
                String query = "SELECT * FROM tbl_admin WHERE u_id = " + userId;
                ResultSet rs = db.getData(query);
 
                if (rs.next() && rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, "Selected employee does not exist!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
                }   
            } catch (SQLException ex) {
                System.out.println(""+ex);
            }
            
            db.updateData ("UPDATE tbl_department SET dep_name = '"+dpname.getText()+"', dep_totalemp = '"+totalemp.getText()+"', dep_userid = '"+userId+"' WHERE dep_id = '"+depid.getText()+"'");
                Session sess = Session.getInstance();
                db.logActivity(sess.getUid(), "Updated a Departmen: " + dpname.getText());                
                JOptionPane.showMessageDialog(this, "Department Updated successfully!");
                departmentForm df = new departmentForm();
                df.setVisible(true);
                this.dispose();
            
        }
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setBackground(nav);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setBackground(bodycolor);
    }//GEN-LAST:event_saveMouseExited

    private void dpheadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpheadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpheadActionPerformed

    private void cnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseClicked
        departmentForm df = new departmentForm();
        df.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cnlMouseClicked

    private void cnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseEntered
        cnl.setBackground(nav1);
    }//GEN-LAST:event_cnlMouseEntered

    private void cnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseExited
       cnl.setBackground(bodycolor1);
    }//GEN-LAST:event_cnlMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    Session sess = Session.getInstance();
        if(sess.getUid() == 0){
            ErrorPage ep = new ErrorPage();
            ep.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowActivated

    private void dpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editDepartmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cnl;
    public javax.swing.JTextField depid;
    public javax.swing.JComboBox<String> dphead;
    public javax.swing.JTextField dpname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel save;
    public javax.swing.JTextField totalemp;
    // End of variables declaration//GEN-END:variables
}
